version: '3.5'

services:
  mysql:
    image: pelando-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword
      MYSQL_DATABASE: pelando
      MYSQL_USER: MainUser
      MYSQL_PASSWORD: MainPassword
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    # volumes:
    #   - db-volume:/var/lib/mysql
  
  app:
    image: pelando
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"

# volumes:
#     db-volume:
